### ISSUE TITLE
Multiple Match for sequence identifier

### ISSUE THREAD

**Issue by dukanto** [crossplane-contrib/function-sequencer#24]
### What problem are you facing?
Function Sequencer works great when all composition-resources name are known, since you know the names of the resources that will be created and, therefore, sort them in desired order.
However, when building dynamic resources (i.e. in a loop in go-templating function), names are not static, and can't be added to sequencer, resulting in those resources not being taken into account in the function.

As a use case, imagine that you create an EKS cluster and N nodegroups (as many as the user desires).
The logic order should be:
- Other resources (e.g. Roles)
- Cluster
- Nodegroups
- More resources

Since Nodegroups have to be created after Cluster is finished

### How could this Function help solve your problem?
Some sort of "wildcard" could be added to the list, and treat all those resources as *one* entity in order to decide wether to continue or not.
That is: 
```yaml
 - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
      - sequence:
        - cluster-role
        - eks-cluster
        - nodegroup-* # will treat all that begins with nodegroup-
```

So, if our composition creates 3 different nodegroups, function will wait for nodegroup-0, nodegroup-1 & nodegroup-2 to be all ready to continue to next step.

**If this approach makes sense, I can provide a PR with an implementation for this :)**

**Comment by eric-carlsson** [comment]
I have similar use cases and think the general idea is sound, but I also see some potential issues with the "wildcard approach". For example:

- How do we handle wildcards that are not at the end of the resource name?
  ```yaml
   - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
        - sequence:
          - eks-cluster-*-cluster-role
  ```
  This is a contrived example and could easily be refactored, but I think we should have a clear approach to how we handle it in general.  
- Furthermore, how do we handle the presence of multiple wildcard characters? For example, consider a composition similar to the example above that creates _multiple_ clusters. Do we allow something like this?
  ```yaml
   - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
        - sequence:
          - cluster-role-*
          - eks-cluster-*
          - eks-cluster-*-nodegroup-*
  ```
- What does it mean to have a sequence that contains multiple resources with wildcards? In the example above, does `eks-cluster-*` wait on _all_ resources that match `cluster-role-*` or only one of them? Intuitively I would expect the earlier, but this should be explicit.

A (perhaps naive) approach would be to use the provided resource name as a standard regex pattern. That would allow expressing both simple and complex sequence relationships. The original example could then be expressed like:

```yaml
 - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
      - sequence:
        - cluster-role
        - eks-cluster
        - "nodegroup-\\d+"
```

Which is all well defined regex. Alternatively we could accept an object instead of a string:

```yaml
 - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
      - sequence:
        - cluster-role
        - eks-cluster
        - type: pattern
          pattern: "nodegroup-\\d+"
```

Which would let us maintain backwards compatibility. Such an approach could also let us specify an explicit strategy which would solve the lack of clarity mentioned in the last bullet point.

**Comment by dukanto** [comment]
Hi, @eric-carlsson 
You are right. I proposed the wildcard as a quick way to explain my point. 
I think that having a full regex approach will be far more clear.

> * Furthermore, how do we handle the presence of multiple wildcard characters? For example, consider a composition similar to the example above that creates _multiple_ clusters. Do we allow something like this?
>   ```yaml
>    - step: sequence-creation
>       functionRef:
>         name: function-sequencer
>       input:
>         apiVersion: sequencer.fn.crossplane.io/v1beta1
>         kind: Input
>         rules:
>         - sequence:
>           - cluster-role-*
>           - eks-cluster-*
>           - eks-cluster-*-nodegroup-*
>   ```
> * What does it mean to have a sequence that contains multiple resources with wildcards? In the example above, does `eks-cluster-*` wait on _all_ resources that match `cluster-role-*` or only one of them? Intuitively I would expect the earlier, but this should be explicit.


I think that every single pattern in sequence must wait on _all_ resources that match on it. So every eks-role-* should wait until all cluster-role-* are ready.

> Which is all well defined regex. Alternatively we could accept an object instead of a string:
> 
> ```yaml
>  - step: sequence-creation
>     functionRef:
>       name: function-sequencer
>     input:
>       apiVersion: sequencer.fn.crossplane.io/v1beta1
>       kind: Input
>       rules:
>       - sequence:
>         - cluster-role
>         - eks-cluster
>         - type: pattern
>           pattern: "nodegroup-\\d+"
> ```
> 
> Which would let us maintain backwards compatibility. Such an approach could also let us specify an explicit strategy which would solve the lack of clarity mentioned in the last bullet point.
> 
> ```yaml
>    - step: sequence-creation
>       functionRef:
>         name: function-sequencer
>       input:
>         apiVersion: sequencer.fn.crossplane.io/v1beta1
>         kind: Input
>         rules:
>         - sequence:
>           - type: pattern
>             pattern: "^cluster-role-\\d+$"
>           - type: pattern
>             pattern: "^eks-cluster-\\d+$"
>           - type: pattern
>             pattern: "^eks-cluster-\\d+-nodegroup-\\d+$"
>             strategy: matchAll # Explicitly require all resources matched earlier in the sequence to have been created. Alternatively this could be "matchOne" etc.
> ```
> 
> Bad example, but hopefully the idea is conveyed.

In this approach I see a bit of a problem, I think that your approach is more extensible, of course, but it'd see it as something more generic like:
```yaml
   - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
        - sequence:
          - type: pattern
             key: "^cluster-role-\\d+$"
          - type: exactMatch    # this would be default and can be omitted.
             key: "this-should-be-exact-match" 
          - type: pattern
            key: "^eks-cluster-\\d+$"

```
The thing I see here is if we want to keep some consistency, it'll be ideal to have some kind of uniformity in the elements of the sequence, but that would force users to migrate.


Here, I don't know which approach is best, but I'll be happy to work on any of them if everyone reachs an agreement on it. Perhaps @turkenh can provide better insight on this :)

**Comment by eric-carlsson** [comment]
> I think that every single pattern in sequence must wait on all resources that match on it. So every eks-role-* should wait until all cluster-role-* are ready.

I don't think that's always the case. For example, when deploying an application or a piece of infrastructure with redundancy I often don't care if all instances are ready before sending them traffic, I just care that _any_ of them are ready. I can agree that waiting on all matched resources to be ready is a sane default, but I also think we should allow users to change that behavior.

> The thing I see here is if we want to keep some consistency, it'll be ideal to have some kind of uniformity in the elements of the sequence, but that would force users to migrate.

Perhaps an in-between solution is to promote the API to v2 with these changes and maintaining the v1 API with its current feature set.

**Comment by callum-stakater** [comment]
this is a needed feature to make this function usable and if added not just usable but extremely useful, as there seems to be a big shift underway from static function-patch-and-transform type compositions toward more dynamic approaches like the as mentioned go-templating or kcl etc and in current state this isnt usable

my opinion on the above discussion would be to keep it simple, allow regex expressions to match all and treat them like they were statically listed (eg wait for all matches), its then up to the user to name their resources in an efficient way if certain resources  of a specific type dont need to be created in specific order - eg using a numbering scheme in resource names/ids for example and regex to match all resources of a numbered wave seems simple and effective

**Comment by eric-carlsson** [comment]
> eg using a numbering scheme in resource names/ids for example and regex to match all resources of a numbered wave seems simple and effective

Could you post an example? I don't directly see how that could solve the above-mentioned scenario. If it can, then that's of course a much simpler and preferred solution. Then we could maybe even get away with implementing this functionality without changing the API.

**Comment by dukanto** [comment]
Hi, @callum-stakater I definitely agree with you on that, in order to provide simplicity, it should be up to the user to provide a schema that has some sort of "logic" in order to adjust the regex as much as possible. 
@eric-carlsson, I will try to reproduce what I think we are talking about below (please, @callum-stakater, correct me if you weren't talking about this specifically).

So, lets imagine a scenario where you have to:
1. create an EKS cluster
2. The user can select a list of roles to add to the cluster in the claim/composite. So, there can be 0-n cluster-roles added (these, thus, should be dynamic)
3. After all those resources are ready, we want to create a helm object and deploy some application in the cluster (this should be created after all the resources above, to ensure all permissions are setted correctly).

Something like this (extremely simplified and omitted for brevity, of course):
```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: my-awesome-composition
  labels:
    component: cluster
    provider: aws
    channel: alpha
spec:
  compositeTypeRef:
    apiVersion: awscluster.myorg.com/v1
    kind: XCluster
  mode: Pipeline
  pipeline:
    - step: eks-cluster
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: eks.aws.upbound.io/v1beta1
            kind: Cluster
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: eks-cluster
              name: {{ index $composite.metadata.labels "crossplane.io/composite" }}
            spec:
              // omitted for brevity
    - step: cluster-roles
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $composite := .observed.composite.resource }}
            {{- for $i, $role := $composite.spec.parameters.roles }}
            ---
            apiVersion: iam.aws.upbound.io/v1beta1
            kind: Role
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: cluster-role-{{ $i }}
              name: cluster-role-{{ $i }}
            spec:
              // omitted for brevity
            {{- end }}

    - step: deploy-app
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $composite := .observed.composite.resource }}
            ---
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: cluster-apps
            spec:
              // omitted for brevity

    #! detect readiness
    - step: detect-readiness
      functionRef:
        name:  function-auto-ready
    #! sequence objects :)
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - eks-cluster
            - cluster-role-*
            - cluster-apps
```


As you can see, when generating the composition, the user is specifying the name of the resources `gotemplating.fn.crossplane.io/composition-resource-name: cluster-role-{{ $i }}` and then waiting explicitly on those in ` - cluster-role-*` 

If the user decides to create another group, it's up to him/her to create another "group name" and the regex that satisfies that group.

Hopes this gives a bit more of context :)


PS: Sorry for the delay on my response, I was out on holidays and took a time to disconnect from code :)

**Comment by callum-stakater** [comment]
@dukanto you got it, sorry i started writing up some examples some days ago, got side tracked and then completely forgot 

but yes that illustrates my point perfectly, thanks

**Comment by eric-carlsson** [comment]
Hi, I'm happy to see this moved forward since it's a necessary feature of the package, but I do have a few concerns:

- #28 is a breaking change, and this is not clearly documented. When `re.MatchString` is given the pattern `cluster-role-*`, it will match the pattern in any part of the key, not just the prefix. There are very real cases where this can cause unintentional behavior. For example I have something very close to `user` and `user-role` as keys for two different resources, and now using "user" as key will match both. This is not expected when upgrading to a new minor version.
- The provided examples are not accurate, `first-subresource-*` will not match `first-subresource-1`, but `first-subresource-.*` will. Additionally, since there's no way to opt out of regex parsing you need to surround fixed patterns with anchors to ensure they are interpreted as fixed, e.g. `^resource$`, which is also not mentioned.

**Comment by dukanto** [comment]
Hi, @eric-carlsson 
Great catch on those points, thank you!
I've opened the following PR, that addresses both issues: https://github.com/crossplane-contrib/function-sequencer/pull/30

Basically, if users declares an open-ended regex (no start nor end), function will only match it fixed `^resource$` effectively making this implementation fully retrocompatible,

What do you think?

**Comment by eric-carlsson** [comment]
Looks good to me @dukanto.

Some corner cases will remain backwards incompatible, such as when the key contains regex special characters, but I think we can assume those will be rare. Still, including a compatibility note in the release change-log seems like a good idea, but it's up to the maintainers.

**Comment by jlemoingora** [comment]
Hi @dukanto,

Thank you for this really useful feature!

I conducted some tests using the provided example: example/composition-regex.yaml (with the 2.0.1 version)

I have a question regarding the creation order of resources. During my test, the second-object is created simultaneously with first-subresource-1 and first-subresource-2. The third-resource is created correctly after the second-object is ready.

From my understanding, the second-object should wait for both first-subresource-1 and first-subresource-2 to be ready before its creation. Maybe i'm wrong ? What could be the issue?

Thank you for your help!

**Comment by dukanto** [comment]
Hey, @jlemoingora 
I just tested it and it's acting like you said, when it should wait for all firsts to be ready until second.
It missed the tests for some reason.
I'll put a fix on it, hopefully by tommorrow :)

Thanks for the catch, and sorry for the inconvenience

**Comment by ashishkurian** [comment]
@dukanto 

I have a sequence as follows. For the resources **NodeConfiguration-***, I am looping inside a for loop to create all the resources that I need. But in the composite resource I get the message like

` 
Pipeline step "sequence-creation": Delaying creation of resource(s) matching "NodeConfigurationDefault" because "NodeConfiguration-*" does not exist yet
`

I think during the conception of the composite, the resource names are not evaluated and thus the functions skips the creation of NodeConfigurationDefault.

Am I missing something or this feature is not supported yet?

![image](https://github.com/user-attachments/assets/065f5407-12aa-4cc8-9a6e-ca7791d8cbdb)

**Comment by ashishkurian** [comment]
@dukanto Sure. Please find it attached.

```yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcastainodeconfiguration.mycompany.com
spec:
  compositeTypeRef:
    apiVersion: mycompany.com/v1alpha1
    kind: XCastAINodeConfiguration
  mode: Pipeline
  pipeline:
  - step: castai-nodeconfigurations
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $eksClusterName     := .observed.composite.resource.spec.genericParameters.eksClusterName }}
          {{- $deletionPolicy     := .observed.composite.resource.spec.genericParameters.deletionPolicy }}
          {{- $providerConfigRef  := .observed.composite.resource.spec.genericParameters.providerConfig }}
          {{- $EksClusterIdId     := .observed.composite.resource.spec.EksClusterId }}
          {{- $envType := .observed.composite.resource.spec.genericParameters.environmentType }}
          {{- $subnetIDOne := .observed.composite.resource.spec.genericParameters.subnetIDOne }}
          {{- $subnetIDTwo := .observed.composite.resource.spec.genericParameters.subnetIDTwo }}
          {{- $EbsKmsKey := .observed.composite.resource.spec.genericParameters.EbsKmsKey }}
          {{- $appUuid := .observed.composite.resource.spec.genericParameters.appUuid }}
          {{- $eksSecurityGroupId := .observed.composite.resource.spec.genericParameters.eksSecurityGroupId }}
          {{- $eksKubernetesVersion := .observed.composite.resource.spec.genericParameters.eksKubernetesVersion }}
          {{- $EksClusterIdId := .observed.composite.resource.spec.eksClusterId.id  }}
          {{- $instanceProfileArn := .observed.composite.resource.spec.instanceProfileParameters.instanceProfileArn }}
          {{- $instanceProfileRoleArn := .observed.composite.resource.spec.instanceProfileParameters.instanceProfileRoleArn }}
          
          # Here I loop over the values from the claim to create multiple nodeconfigurations
          {{ with $nodeConfigurations := .observed.composite.resource.spec.nodeConfigurations }}
          {{ range $nodeConfiguration := $nodeConfigurations }}
          ---
          apiVersion: castai.upbound.io/v1alpha1
          kind: NodeConfiguration
          metadata:
            name: {{$nodeConfiguration.name}}
            labels:
              cast-ai-cluster: {{$eksClusterName}}-{{$nodeConfiguration.name}}
              nodeconfiguration-name: {{$nodeConfiguration.name}}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: NodeConfiguration-{{$nodeConfiguration.name}}
              crossplane.io/paused: "false"
          spec:
            deletionPolicy: {{$deletionPolicy}}
            providerConfigRef:
              name: {{$providerConfigRef}}
            forProvider:
              eks:
                - securityGroups: [{{$eksSecurityGroupId}}]
                  instanceProfileArn: {{$instanceProfileArn}}
                  nodeGroupArn: {{$instanceProfileRoleArn}}
                  ipsPerPrefix: 16

                  {{- if (ne $nodeConfiguration.volumeType nil) }}
                  volumeType: {{$nodeConfiguration.volumeType | quote}}
                  {{- else }}
                  volumeType: "gp3"
                  {{- end }}

                  volumeKmsKeyArn: {{$EbsKmsKey}}
                  imdsV1: false
                  maxPodsPerNodeFormula: "NUM_MAX_NET_INTERFACES * (NUM_IP_PER_INTERFACE - 1) * NUM_IP_PER_PREFIX + 2"
              image: bottlerocket-aws-k8s-{{$eksKubernetesVersion}}-x86_64*
              containerRuntime: "containerd"
              
              {{- if (ne $nodeConfiguration.drainTimeoutSec nil) }}
              drainTimeoutSec: {{$nodeConfiguration.drainTimeoutSec}}
              {{- else }}
              drainTimeoutSec: 1200
              {{- end }}

              {{- if (ne $nodeConfiguration.diskCpuRatio nil) }}
              diskCpuRatio: {{$nodeConfiguration.diskCpuRatio}}
              {{- else }}
              diskCpuRatio: 0
              {{- end }}

              {{- if (ne $nodeConfiguration.minDiskSize nil) }}
              minDiskSize: {{$nodeConfiguration.minDiskSize}}
              {{- else }}
              minDiskSize: 100
              {{- end }}

              name: {{$nodeConfiguration.name}}
              clusterId: {{$EksClusterIdId}}
              subnets:
                 - {{$subnetIDOne}}
                 - {{$subnetIDTwo}}
              tags:
                {
                  "sc:env": {{$envType}},
                  "sc:app-uuid": {{$appUuid}}
                }
          {{ end }}
          {{ end }}
  - step: castai-nodeconfiguration-default
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $eksClusterName     := .observed.composite.resource.spec.genericParameters.eksClusterName }}
          {{- $deletionPolicy     := .observed.composite.resource.spec.genericParameters.deletionPolicy }}
          {{- $providerConfigRef  := .observed.composite.resource.spec.genericParameters.providerConfig }}
          {{- $EksClusterIdId := .observed.composite.resource.spec.eksClusterId.id  }}

          {{ $managedresources    := .observed.resources | default dict }}
          {{ $NodeConfigurationDefault := get $managedresources "NodeConfiguration-default" | default dict }}
          {{ $NodeConfigurationDefaultId      := dig "resource" "status" "atProvider" "id" "defaultvalue" $NodeConfigurationDefault }}
          ---
          apiVersion: castai.upbound.io/v1alpha1
          kind: NodeConfigurationDefault
          metadata:
            name: defaultnodeconfiguration
            labels:
              cast-ai-cluster: {{$eksClusterName}}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: NodeConfigurationDefault
              crossplane.io/paused: "false"
          spec:
            deletionPolicy: {{$deletionPolicy}}
            providerConfigRef:
              name: {{$providerConfigRef}}
            forProvider:
              clusterId: {{$EksClusterIdId}}
              configurationId: {{$NodeConfigurationDefaultId}}
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
  - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
        - sequence:
          - NodeConfiguration-*
          - NodeConfigurationDefault
```

**Comment by dukanto** [comment]
@ashishkurian 
Found it!

The regex of `NodeConfiguration-*` is wrong.
It should be `NodeConfiguration-.*` (notice the dot)

If you use fix it like this:
```
  - step: sequence-creation
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      rules:
        - sequence:
          - NodeConfiguration-.*
          - NodeConfigurationDefault
```

You'll see the following message (which is correct):
`
2024-12-12T10:18:42.665+0100	INFO	function-sequencer/fn.go:111	Delaying creation of resource(s) matching "NodeConfigurationDefault" because "NodeConfiguration-.*" is not fully ready (0 of 2)
`
