### ISSUE TITLE
crossplane render with 3 sequences not rendering all resources

### ISSUE THREAD

**Issue by FACOLOMBANI** [crossplane-contrib/function-sequencer#36]
### What happened?
I have 3 sequences as described below, component2 depends on component1 and the rest of components depend on component2.

```
        rules:
          - sequence:
              - component1
              - component2
              - component3
          - sequence:
              - component1
              - component2
              - component4
          - sequence:
              - component1
              - component2
              - component5
```

When running crossplane render it only renders xr and component1. and when i check the observed resources after component1 i have repetitions of 

```
apiVersion: render.crossplane.io/v1beta1
kind: Result
message: Delaying creation of resource "component3" because "component1" is not ready or does not exist yet
severity: SEVERITY_NORMAL
step: sequence-creation
---
apiVersion: render.crossplane.io/v1beta1
kind: Result
message: Delaying creation of resource "component4" because "component1" is not ready or does not exist yet
severity: SEVERITY_NORMAL
step: sequence-creation
---
apiVersion: render.crossplane.io/v1beta1
kind: Result
message: Delaying creation of resource "component5" because "component1" is not ready or does not exist yet
severity: SEVERITY_NORMAL
step: sequence-creation
```

### How can we reproduce it?
I am following your examples, what i don't have is the conditions part because my provider does not set at one status as ready, and i cannot set the forProvider section with conditions

### What environment did it happen in?
local environment
Function version: 0.2.1
crossplane version: v0.18.0
kubernetes version: v1.31.0
OS: mac m1 pro
Kernel: Darwin Kernet Version 24.1.0
